[app]
  environment = "development"
  listen_address = "0.0.0.0:9527"
  otp_required = true
  auth_providers = ["telegram"]

[channels]
  [channels.telegram]
    bot_token = "Your Telegram Bot Token"
    recipients = [1231321]

  [channels.http]
    endpoint = "https://httpbin.org/post"

    [channels.http.headers]
      Authorization = "Bearer 1234567890"
      Content-Type = "application/json"

  [channels.email]
    smtp_host = "smtp.example.com"
    smtp_port = 587
    smtp_username = "user@example.com"
    smtp_password = "app_password"
    from = "sigmo@example.com"
    recipients = ["ops@example.com"]
    subject = "Sigmo Notification"
    tls_policy = "mandatory"
    ssl = false
